"""Character identity, policy, context, generation, and state boundaries."""

from .autonomy import (
    AUTONOMY_PROMPT_VERSION,
    AutonomyAction,
    AutonomyDecision,
    AutonomyGuard,
    AutonomyGuardConfig,
    AutonomyGuardResult,
    AutonomyOpportunity,
    AutonomyOpportunityScheduler,
    AutonomyPlanner,
    AutonomyScheduleConfig,
    AutonomySignal,
    AutonomySignalKind,
)
from .autonomy_generation import (
    AUTONOMY_MESSAGE_PROMPT_VERSION,
    AutonomyMessageGenerationError,
    AutonomyMessageGenerator,
)
from .context import (
    CHARACTER_PROMPT_VERSION,
    BuiltCharacterContext,
    CharacterContextBuilder,
    CharacterContextSources,
)
from .generator import CharacterGenerationError, CharacterGenerator
from .legacy_persona import LegacyPersona, PersonaLoadError, load_legacy_persona
from .persona import (
    LoadedPersonaCore,
    PersonaCore,
    PersonaCoreLoadError,
    PersonaTrigger,
    load_persona_core,
)
from .policy import (
    POLICY_PROMPT_VERSION,
    AnswerObligation,
    ConversationAct,
    ConversationPolicy,
    ConversationPolicyPlanner,
    PolicyContext,
    render_policy_instruction,
)
from .retrospective import (
    RETROSPECTIVE_PROMPT_VERSION,
    CharacterRetrospective,
    RetrospectiveAction,
    RetrospectiveContext,
    RetrospectiveDecision,
    RetrospectiveMessage,
    RetrospectiveResult,
    RetrospectiveTriggerContext,
    RetrospectiveTriggerPolicy,
)
from .spontaneity import (
    SPONTANEITY_PROMPT_VERSION,
    SpontaneityAction,
    SpontaneityComposer,
    SpontaneityConfig,
    SpontaneityDecision,
    SpontaneityOpportunity,
    SpontaneityOpportunityGate,
)
from .state import (
    AssumptionStatus,
    CharacterState,
    CharacterStateSnapshot,
    MistakeScope,
    PlausibleMistake,
    StateResidue,
    WorkingAssumption,
)
from .state_store import SQLiteCharacterStateStore
from .turn_engine import (
    CharacterTurnEngine,
    CharacterTurnInput,
    CharacterTurnResult,
    CharacterTurnTiming,
)

__all__ = [
    "AUTONOMY_MESSAGE_PROMPT_VERSION",
    "AUTONOMY_PROMPT_VERSION",
    "CHARACTER_PROMPT_VERSION",
    "POLICY_PROMPT_VERSION",
    "RETROSPECTIVE_PROMPT_VERSION",
    "SPONTANEITY_PROMPT_VERSION",
    "AnswerObligation",
    "AssumptionStatus",
    "AutonomyAction",
    "AutonomyDecision",
    "AutonomyGuard",
    "AutonomyGuardConfig",
    "AutonomyGuardResult",
    "AutonomyMessageGenerationError",
    "AutonomyMessageGenerator",
    "AutonomyOpportunity",
    "AutonomyOpportunityScheduler",
    "AutonomyPlanner",
    "AutonomyScheduleConfig",
    "AutonomySignal",
    "AutonomySignalKind",
    "BuiltCharacterContext",
    "CharacterContextBuilder",
    "CharacterContextSources",
    "CharacterGenerationError",
    "CharacterGenerator",
    "CharacterRetrospective",
    "CharacterState",
    "CharacterStateSnapshot",
    "CharacterTurnEngine",
    "CharacterTurnInput",
    "CharacterTurnResult",
    "CharacterTurnTiming",
    "ConversationAct",
    "ConversationPolicy",
    "ConversationPolicyPlanner",
    "LegacyPersona",
    "LoadedPersonaCore",
    "MistakeScope",
    "PersonaCore",
    "PersonaCoreLoadError",
    "PersonaLoadError",
    "PersonaTrigger",
    "PlausibleMistake",
    "PolicyContext",
    "RetrospectiveAction",
    "RetrospectiveContext",
    "RetrospectiveDecision",
    "RetrospectiveMessage",
    "RetrospectiveResult",
    "RetrospectiveTriggerContext",
    "RetrospectiveTriggerPolicy",
    "SQLiteCharacterStateStore",
    "SpontaneityAction",
    "SpontaneityComposer",
    "SpontaneityConfig",
    "SpontaneityDecision",
    "SpontaneityOpportunity",
    "SpontaneityOpportunityGate",
    "StateResidue",
    "WorkingAssumption",
    "load_legacy_persona",
    "load_persona_core",
    "render_policy_instruction",
]
